#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only

egrep -q '^%zimbra[[:space:]]' /etc/sudoers
if [ $? = 0 ]; then
  sudotmp=`mktemp -t zsudoers.XXXXXX 2> /dev/null` || { echo "Failed to create tmpfile"; exit 1; }
  SUDOMODE=`perl -e 'my $mode=(stat("/etc/sudoers"))[2];printf("%04o\n",$mode & 07777);'`
  egrep -v '^%zimbra[[:space:]]' /etc/sudoers > $sudotmp
  mv -f $sudotmp /etc/sudoers
  chmod $SUDOMODE /etc/sudoers
fi
chmod 440 /etc/sudoers.d/02_zimbra-proxy
chown root:root /etc/sudoers.d/02_zimbra-proxy
chown -R zimbra:zimbra /opt/zimbra/conf/nginx
